"Second header" optional (fix for a part of #67)
siddhantgoel/beancount-ing-diba pull request #73
Opened 2021-05-02 19:18 UTC by szabootibor

2021-05-02 19:36 UTC, szabootibor commented
I'm just fixing the flake8 errors

2021-05-02 19:37 UTC, siddhantgoel requested changes

2021-05-02 19:37 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
> -                raise InvalidFormatError()
As I understand, this PR is aimed at fixing the problem with the optional "Letztes Update" header line. To fix that, wouldn't replacing just these two lines with the changes you made to `identify` be enough?

I'm trying to understand why this PR also replaces the current logic with the new logic with the array of dicts format.

2021-05-02 19:57 UTC, szabootibor commented on beancount_ing_diba/ec.py
> -                raise InvalidFormatError()
1. Well, it would be enough. However, I tried to consider your proposal https://github.com/siddhantgoel/beancount-ing-diba/issues/69#issuecomment-829566498 . The implementation is probably even more general and does not expect "segments" separated by empty lines. It also steps over metadata lines. with unknown key.
2. the "array of dicts" format eases tracking of line numbers, which became somewhat clumsy with the new read logic.

2021-05-02 20:06 UTC, szabootibor commented on beancount_ing_diba/ec.py
> -                raise InvalidFormatError()
(I just ignored empty lines and read all content by `csv.reader` until `In der CSV-Datei finden Sie alle...`, this way loosing the 1:1 mapping between the output array elements of `csv.reader `and line numbers)

2021-05-02 20:27 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
> -                raise InvalidFormatError()
Thanks for the quick update. Could we actually do this rewrite in a separate PR and limit this one strictly to the optional header line?

1. That's what the format is though, right? Three segments separated by empty lines? This is also evident in, eg. `transaction_data = lines[i+2:]` where you assume that there's an empty line before which the transactions start. I ask because instead of accounting for such special cases, we could just treat the file as being composed of three sections and avoid the special cases altogether. Or is there a specific disadvantage you see of reading the file into three separate lists?
2. I guess it'll depend on what approach we end up taking, but generally speaking, Python also has an inbuilt [`enumerate`](https://docs.python.org/3.8/library/functions.html#enumerate) function which gives you indices when iterating.

PS: I'm just trying my best to keep the complexity of this package low. I know that this package is not much more than a quick integration script and we don't have to optimize for code quality here, but keeping this code easy to read/understand helps a ton with maintaining.

2021-05-04 18:15 UTC, szabootibor commented on beancount_ing_diba/ec.py
> -                raise InvalidFormatError()
Here you go

2021-05-05 05:38 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
> -                raise InvalidFormatError()
Nice, thank you!

2021-05-05 05:39 UTC, merged