Generate balance assertions (solution for #69)
siddhantgoel/beancount-ing-diba pull request #74
Opened 2021-05-06 20:38 UTC by szabootibor

2021-05-09 09:37 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
>                      self._balance = Amount(_format_number_de(amount), currency)
If this is not useful, we can also remove it entirely.

2021-05-09 09:38 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
> +                    )
I wonder if we need to rely on this sorting. Each transaction has a date associated with it. We can use that date to determine the starting and closing dates and the associated balance amounts.

2021-05-09 09:49 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
> +                    first_transaction = last_transaction
We could also use the `line['Buchung']` value here, if I understood this correctly? Then we could avoid the need to rely on the sorting. Something like the following:

```python
date_first_transaction = date_last_transaction = None
first_transaction = last_transaction = None

date = line['Buchung']

# ...

date = datetime.strptime(date, '%d.%m.%Y').date()

# ... initialize transaction

if date_first_transaction is None or date <= date_first_transaction:
    date_first_transaction = date
    first_transaction = transaction

if date_last_transaction is None or date >= date_last_transaction:
    date_last_transaction = date
    last_transaction = transaction
```

... and then we can use the `date_first_transaction` and `date_last_transaction` variables to generate balance directives (the values and the currencies could come from the `first_transaction` and `last_transaction` entries).

I think the usage of `<=` and `>=` should be OK because the Saldo associated with all the transactions on the same day should be the same. My personal account usually has never more than 1 transaction per month so I unfortunately cannot verify this.

2021-05-09 20:15 UTC, szabootibor commented on beancount_ing_diba/ec.py
>                      self._balance = Amount(_format_number_de(amount), currency)
OK

2021-05-09 20:43 UTC, szabootibor commented on beancount_ing_diba/ec.py
> +                    first_transaction = last_transaction
The `Saldo` column of a transaction line is a rolling balance; i.e. it is the balance of the account just after committing this single transaction, and not the closing balance on that day. Example:

```
Transaction 1: Datum: 10.05.2021; Betrag: -100 €; Saldo: 500 €
Transaction 2: Datum: 10.05.2021; Betrag: -200 €; Saldo: 300 €
```
Based on these 2 transaction we can assert the opening balance on 10.05.2021: 600 € and the opening balance on 11.05.2021: 300 €, provided that no more transactions will be booked after generating this report on 10.05.2021.

But if the ordering of these transactions in the report is different from the order of their occurrence, then we must chain them in a way that the pre-transaction balance (`Saldo minus Betrag`) of transaction 2 is equal to the post-transaction balance (`Saldo`) of transaction 1. Depending on the amounts the ordering may be ambiguous. Nevertheless I think it would be possible to find the closing balance unambiguously. Instead of solving this problem I proposed to require to order the transactions by date in the input data in order to emit balance assertions.

I also used the dates from the `Zeitraum` metadata, because it allows the balance assertions to cover a broader time span yet still be valid. But using the dates of the actual transactions instead is also not wrong.

2021-05-10 15:41 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
> +                    first_transaction = last_transaction
Ah ok, makes sense. That's a messy file format ING DiBa provides us with. :man_shrugging:

In any case, I'll try to have a look at this PR this week. Thanks again for taking this up!

2021-05-11 07:38 UTC, szabootibor commented on beancount_ing_diba/ec.py
> +                    first_transaction = last_transaction
Well I think the format is not so bad. The quirk is that the balance reported in the metadata is valid on the date in the first header line (time of downloading the CSV) and not at the end of the exported time period.

2021-05-13 14:21 UTC, siddhantgoel requested changes
Nice, thanks!

Since there's a bit of calculation going on in generating these balance assertions, could you also add a few tests here? I could imagine at least the following scenarios we should consider:

1. sorting is not enabled (then no balance assertions)
2. sorted by ascending date, single transaction
3. sorted by ascending date, multiple transactions on the same date
4. sorted by descending date, single transaction
5. sorted by descending date, multiple transactions on the same date

2021-05-13 14:21 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
> +                    logging.warning(
```suggestion
                    warnings.warn(
```

2021-05-13 14:21 UTC, siddhantgoel commented on beancount_ing_diba/ec.py
> +            def balance_assertion(transaction, opening=False, closing=False):
General question: should we also make sure that the two "Währung" fields have the same value? And in case they're not, then we issue a warning and don't emit a `Balance`? Otherwise we might be operating on two different values.

2021-05-13 19:39 UTC, szabootibor commented on beancount_ing_diba/ec.py
> +            def balance_assertion(transaction, opening=False, closing=False):
Absolutely right.

2021-05-13 21:04 UTC, szabootibor commented
Some testcases were added

2021-05-15 11:30 UTC, merged

2021-05-15 11:30 UTC, siddhantgoel commented
Nice, thanks! I'll try to push a release in the coming days.

2021-05-19 19:24 UTC, siddhantgoel commented
Just published this in `v0.5.0`. Thanks for the MR!